import json
import hashlib
import logging
from typing import List, TypedDict, Dict, Any
from pydantic import BaseModel
from langgraph.graph import StateGraph, START, END
from core.redis import CACHE_TTL

logger = logging.getLogger(__name__)

# --- Data Models ---
class QuizQuestion(BaseModel):
    question: str
    options: List[str]
    correct_answer: str
    explanation: str

class QuizData(BaseModel):
    quiz: List[QuizQuestion]

class GraphState(TypedDict):
    source_text: str
    generated_quiz: dict


# --- The Service Class ---
class QuizService:
    """Service class to handle AI Quiz generation, injecting Redis and the LLM client."""
    
    def __init__(self, redis_client, llm_client):
        self.redis = redis_client
        self.llm = llm_client
        # Compile the graph upon instantiation using the injected LLM
        self.quiz_graph = self._build_graph()

    def _build_graph(self):
        """Constructs the LangGraph using the injected LLM instance."""
        def generate_quiz_node(state: GraphState):
            text = state["source_text"]
            system_prompt = "You are an expert educator. Generate a 3-question multiple-choice quiz based on the provided text."
            
            structured_llm = self.llm.with_structured_output(QuizData)
            
            messages = [
                ("system", system_prompt),
                ("human", f"Generate a quiz based on this text:\n\n{text}")
            ]
            
            result = structured_llm.invoke(messages)
            return {"generated_quiz": result.model_dump()}

        workflow = StateGraph(GraphState)
        workflow.add_node("generator", generate_quiz_node)
        workflow.add_edge(START, "generator")
        workflow.add_edge("generator", END)
        
        return workflow.compile()

    def generate_quiz(self, text: str, user_id: str = "anonymous") -> Dict[str, Any]:
        log_context = {
            "user_id": user_id,
            "action": "quiz_generation",
            "text_length": len(text)
        }

        text_hash = hashlib.md5(text.encode("utf-8")).hexdigest()
        cache_key = f"quiz:{text_hash}"

        try:
            cached = self.redis.get(cache_key)
            if cached:
                log_context["source"] = "redis_cache"
                logger.info("Quiz fetched from cache", extra=log_context)
                return json.loads(cached)

            final_state = self.quiz_graph.invoke({"source_text": text})
            result = final_state["generated_quiz"]

            self.redis.setex(cache_key, CACHE_TTL, json.dumps(result))
            
            log_context.update({
                "source": "llm_generation",
                "questions_count": len(result.get("quiz", []))
            })
            logger.info("Quiz successfully generated by LLM", extra=log_context)
            
            return result

        except Exception as e:
            logger.exception("Failed to generate quiz", extra=log_context)
            raise Exception("Failed to generate quiz.") from e


# --- The Dependency Provider for FastAPI ---
def get_quiz_service() -> QuizService:
    from core.redis import redis_client
    from core.llm import llm
    
    # Injects the real Redis and LLM clients for production
    return QuizService(redis_client=redis_client, llm_client=llm)